# Import Libraries

In [1]:
import nltk
from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer()

import numpy
import tflearn
import tensorflow
import random
import json
import pickle



C:\ProgramData\Anaconda3\envs\chatbot_36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\envs\chatbot_36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\envs\chatbot_36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\envs\chatbot_36\lib\site-packages

curses is not supported on this machine (please install/reinstall curses for an optimal experience)








# Import Dataset

In [2]:
with open("intents.json", encoding='UTF-8') as file:
    data = json.load(file)

In [3]:
data

{'intents': [{'tag': 'name',
   'patterns': ['what is the name of the department?',
    'what is the full form of CSE?',
    'which department is this?'],
   'responses': ['Computer Science & Engineering'],
   'context_set': ''},
  {'tag': 'programs',
   'patterns': ['what programs does this course offer?',
    'what are the programs this course offers?'],
   'responses': ['BSc in CSE, MSc in CSE, M Engg in Computer Science, Ph.D. in CSE'],
   'context_set': ''},
  {'tag': 'MIST',
   'patterns': ['what is the name of this institution?',
    'what is the name of your institution?',
    'What is the full form of MIST?'],
   'responses': ['Military Institute of Science & Technology'],
   'context_set': ''},
  {'tag': 'Faculty',
   'patterns': ['How many faculties are there in CSE department?',
    'what is the strength of faculties of CSE department?'],
   'responses': ['1 Head of the department, 4 Professors, 3 Associate Professors, 6 Assistant Professors and 16 Lecturers'],
   'context_

# Data Preprocessing 

In [4]:
words = []
labels = []
docs_x = []
docs_y = []

for intent in data["intents"]:
    for pattern in intent["patterns"]:
        wrds = nltk.word_tokenize(pattern)
        words.extend(wrds)
        docs_x.append(wrds)
        docs_y.append(intent["tag"])

    if intent["tag"] not in labels:
        labels.append(intent["tag"])

words = [stemmer.stem(w.lower()) for w in words if w != "?"]
words = sorted(list(set(words)))

In [5]:
len(words)

189

In [7]:
words

['.',
 'a',
 'about',
 'addit',
 'admit',
 'and',
 'any',
 'anyon',
 'ar',
 'avail',
 'be',
 'bengal',
 'bsc',
 'bus',
 'calc',
 'can',
 'canteen',
 'carry',
 'choos',
 'class',
 'club',
 'command',
 'complet',
 'compuls',
 'cost',
 'cours',
 'cricket',
 'cse',
 'cyb',
 'depart',
 'diff',
 'distribut',
 'do',
 'doe',
 'dur',
 'end',
 'engl',
 'everyday',
 'exam',
 'expens',
 'facul',
 'fee',
 'field',
 'food',
 'footbal',
 'for',
 'form',
 'from',
 'ful',
 'gam',
 'get',
 'giv',
 'go',
 'gpa',
 'gradut',
 'gym',
 'hal',
 'hav',
 'heard',
 'how',
 'hsc',
 'i',
 'in',
 'individ',
 'institut',
 'is',
 'it',
 'kind',
 'lab',
 'langu',
 'libr',
 'many',
 'mark',
 'me',
 'mist',
 'month',
 'much',
 'nam',
 'numb',
 'of',
 'off',
 'or',
 'outdo',
 'pass',
 'pay',
 'play',
 'playground',
 'prefer',
 'pres',
 'priv',
 'program',
 'provid',
 'publ',
 'qual',
 'quest',
 'quot',
 'result',
 'scholarship',
 'seat',
 'second',
 'serv',
 'should',
 'soon',
 'start',
 'stipend',
 'strength',
 'stud',


In [8]:
len(labels)

40

In [9]:
sorted(labels)

['Clubs',
 'Commandant',
 'Cyber Gym',
 'Department',
 'Department bangla',
 'Faculty',
 'Faculty bangla',
 'GPA',
 'Lab',
 'Library',
 'MIST',
 'MIST_Bangla',
 'admission marks',
 'admission pass mark',
 'calculator',
 'class duration',
 'expenses',
 'food quality',
 'food quality bangla',
 'graduation duration',
 'graduation duration bangla',
 'hall expenses',
 'hall expenses bangla',
 'hall seat',
 'hall seat bnagla',
 'language',
 'marks distribution',
 'name',
 'programs',
 'public',
 'public bangla',
 'reasons to admit',
 'reasons to admit bangla',
 'seat',
 'second time',
 'second time bangla',
 'sports',
 'stipend',
 'transportation',
 'uniform']

In [10]:
docs_x

[['what', 'is', 'the', 'name', 'of', 'the', 'department', '?'],
 ['what', 'is', 'the', 'full', 'form', 'of', 'CSE', '?'],
 ['which', 'department', 'is', 'this', '?'],
 ['what', 'programs', 'does', 'this', 'course', 'offer', '?'],
 ['what', 'are', 'the', 'programs', 'this', 'course', 'offers', '?'],
 ['what', 'is', 'the', 'name', 'of', 'this', 'institution', '?'],
 ['what', 'is', 'the', 'name', 'of', 'your', 'institution', '?'],
 ['What', 'is', 'the', 'full', 'form', 'of', 'MIST', '?'],
 ['How', 'many', 'faculties', 'are', 'there', 'in', 'CSE', 'department', '?'],
 ['what',
  'is',
  'the',
  'strength',
  'of',
  'faculties',
  'of',
  'CSE',
  'department',
  '?'],
 ['How',
  'many',
  'laboratories',
  'are',
  'there',
  'in',
  'CSE',
  'department',
  '?'],
 ['How', 'many', 'laboratories', 'does', 'CSE', 'department', 'have', '?'],
 ['Is',
  'it',
  'true',
  'that',
  'CSE',
  'department',
  'will',
  'be',
  'having',
  'a',
  'cyber',
  'gym',
  'very',
  'soon',
  '?'],
 ['I'

In [37]:
wrds = [stemmer.stem(w.lower()) for w in docs_x[17] if w != "?"]


In [38]:
wrds

['how', 'many', 'depart', 'doe', 'mist', 'hav']

In [13]:
docs_y

['name',
 'name',
 'name',
 'programs',
 'programs',
 'MIST',
 'MIST',
 'MIST',
 'Faculty',
 'Faculty',
 'Lab',
 'Lab',
 'Cyber Gym',
 'Cyber Gym',
 'Cyber Gym',
 'Library',
 'Library',
 'Department',
 'Department',
 'Commandant',
 'Commandant',
 'Clubs',
 'Clubs',
 'public',
 'admission marks',
 'admission marks',
 'language',
 'language',
 'language',
 'marks distribution',
 'marks distribution',
 'GPA',
 'GPA',
 'calculator',
 'calculator',
 'admission pass mark',
 'admission pass mark',
 'transportation',
 'transportation',
 'seat',
 'seat',
 'expenses',
 'expenses',
 'class duration',
 'class duration',
 'hall seat',
 'hall seat',
 'hall expenses',
 'hall expenses',
 'food quality',
 'food quality',
 'graduation duration',
 'uniform',
 'uniform',
 'second time',
 'sports',
 'sports',
 'sports',
 'reasons to admit',
 'reasons to admit',
 'stipend',
 'stipend',
 'MIST_Bangla',
 'MIST_Bangla',
 'reasons to admit bangla',
 'reasons to admit bangla',
 'second time bangla',
 'graduation

In [11]:
labels = sorted(labels)

training = []
output = []

out_empty = [0 for _ in range(len(labels))]

for x, doc in enumerate(docs_x):
    bag = []

    wrds = [stemmer.stem(w.lower()) for w in doc]

    for w in words:
        if w in wrds:
            bag.append(1)
        else:
            bag.append(0)

    output_row = out_empty[:]
    output_row[labels.index(docs_y[x])] = 1

    training.append(bag)
    output.append(output_row)


training = numpy.array(training)
output = numpy.array(output)


In [15]:
training[8]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
len(training[1])

189

In [17]:
output[8]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
with open("data.pickle", "wb") as f:
    pickle.dump((words, labels, training, output), f)

In [23]:
words[29]

'depart'

In [24]:
output[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
training.shape

(78, 189)

In [35]:
output.shape

(78, 40)

# ANN Model

In [12]:
tensorflow.reset_default_graph()

net = tflearn.input_data(shape=[None, len(training[0])])
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, len(output[0]), activation="softmax")
net = tflearn.regression(net)

model = tflearn.DNN(net)


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

Instructions for updating:
keep_dims is deprecated, use keepdims instead

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



In [13]:
ANN=model.fit(training, output, n_epoch=1000, batch_size=8, show_metric=True)
    

Training Step: 9999  | total loss: 0.06660 | time: 0.034s
| Adam | epoch: 1000 | loss: 0.06660 - acc: 0.9965 -- iter: 72/78
Training Step: 10000  | total loss: 0.06048 | time: 0.039s
| Adam | epoch: 1000 | loss: 0.06048 - acc: 0.9969 -- iter: 78/78
--


# Saving The Model

In [30]:
model.save("model.tflearn")

INFO:tensorflow:C:\Users\SHIKHON\Chatbot\Thesis\model.tflearn is not in all_model_checkpoint_paths. Manually adding it.


# Data Preprocessing of User Input

In [8]:
def bag_of_words(s, words):
    bag = [0 for _ in range(len(words))]

    s_words = nltk.word_tokenize(s)
    s_words = [stemmer.stem(word.lower()) for word in s_words]

    for se in s_words:
        for i, w in enumerate(words):
            if w == se:
                bag[i] = 1
    test = numpy.array(bag)    
    
    return test

In [9]:
def chat():
    print("Start talking with the bot (type quit to stop)!")
    while True:
        inp = input("You: ")
        if inp.lower() == "quit":
            break

        results = model.predict([bag_of_words(inp, words)])[0]
        results_index = numpy.argmax(results)
        tag = labels[results_index]

        if results[results_index] > 0.5:

            for tg in data["intents"]:

                if tg['tag'] == tag:
                    responses = tg['responses']

            
            result = random.choice(responses)
            print(result)
        else:
            
            print("i didn't get it. Ask another question")

# Chat

In [ ]:
chat()

Start talking with the bot (type quit to stop)!
You: name of the department
Computer Science & Engineering
You: class duration
i didn't get it. Ask another question
You: what is the class duration
In general classes start at 8:00 hours and end at 14:40 hours. But mostly class duration depends on the routine. There may be class or lab after 14:40 hours which is quite rare.
You: Is hall seat available
Mist has Osmany Hall which is divided into two part : male wing and female wing. Besides if the student number exceeds the number of seat in Osmany hall, Mist authority manages extension hall in Mirpur DOHS. So hall seat is always available but sometimes it can take some time to get a seat.
You: hall expenses
i didn't get it. Ask another question
You: monthly fee of the hall expenses
Students have to pay Tk.2700 per month for hall fee. Dining bill is separated and students have to pay for their meal if they sign for meal.
You: food quality in canteen
Mist authority always cares about the qu

In [10]:
chat()

Start talking with the bot (type quit to stop)!
You: food quality  in canteen
Mist authority always cares about the quality of food in both canteen and hall.
You: quit
